// Post User
export const REQUEST_USER_DATA = 'REQUEST_USER_DATA';
export const RECEIVED_USER_DATA = 'RECEIVED_USER_DATA';
export const ERROR_USER_DATA = 'ERROR_USER_DATA';

// Get Latest Feed
export const REQUEST_LATEST_ARTICLES_DATA = 'REQUEST_LATEST_ARTICLES_DATA';
export const RECEIVED_LATEST_ARTICLES_DATA = 'RECEIVED_LATEST_ARTICLES_DATA';
export const ERROR_LATEST_ARTICLES_DATA = 'ERROR_LATEST_ARTICLES_DATA';

// Get Feed
export const REQUEST_ARTICLES_DATA = 'REQUEST_ARTICLE_DATA';
export const RECEIVED_ARTICLES_DATA = 'RECEIVED_ARTICLES_DATA';
export const ERROR_ARTICLES_DATA = 'ERROR_ARTICLES_DATA';

// Get Article
export const REQUEST_ARTICLE_DATA = 'REQUEST_ARTICLE_DATA';
export const RECEIVED_ARTICLE_DATA = 'RECEIVED_ARTICLE_DATA';
export const ERROR_ARTICLE_DATA = 'ERROR_ARTICLE_DATA';

// Get Comments
export const REQUEST_COMMENTS_DATA = 'REQUEST_COMMENTS_DATA';
export const RECEIVED_COMMENTS_DATA = 'RECEIVED_COMMENTS_DATA';
export const ERROR_COMMENTS_DATA = 'ERROR_COMMENTS_DATA';

// Post Comment
export const REQUEST_POST_COMMENT = 'REQUEST_POST_COMMENT';
export const RECEIVED_POST_COMMENT = 'RECEIVED_POST_COMMENT';
export const ERROR_POST_COMMENT = 'ERROR_POST_COMMENT';

// Delete Comment
export const REQUEST_DELETE_COMMENT = 'REQUEST_DELETE_COMMENT';
export const RECEIVED_DELETE_COMMENT = 'RECEIVED_DELETE_COMMENT';
export const ERROR_DELETE_COMMENT = 'ERROR_DELETE_COMMENT';
